name = "HEPExampleProject"
uuid = "f779019a-d216-4ac1-8c1a-8c09799cc4e6"
authors = ["Uwe Hernandez Acosta <u.hernandez@hzdr.de>"]
version = "0.0.1-DEV"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[weakdeps]
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[extensions]
PlottingExt = "StatsPlots"

[compat]
QuadGK = "2.11.0"
Random = "1.11.0"
SafeTestsets = "0.1.0"
StatsPlots = "0.15.7"
julia = "1.6"

[extras]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "QuadGK"]
